name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: g++ -O2 cpu_cycles_per_cmd.cpp
        run: g++ -O2 cpu_cycles_per_cmd.cpp -o cpu_cycles_per_cmd.elf
      - name: foobar
        run: |
          ./cpu_cycles_per_cmd.elf
          wget https://raw.githubusercontent.com/gitseo/vm/master/crude/os.js
          wget https://raw.githubusercontent.com/gitseo/vm/master/proc_mem_limit_detector.cpp
          g++ -O2 proc_mem_limit_detector.cpp -o proc_mem_limit_detector.elf
          node --version
          node os.js
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cpu_cycles_per_cmd.elf
          path: cpu_cycles_per_cmd.elf
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: proc_mem_limit_detector.elf
          path: proc_mem_limit_detector.elf
  win32_build:
    name: default
    runs-on: windows-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v1
      - name: ilammy/msvc-dev-cmd@v1
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
      - name: Compile and run some C code
        shell: cmd
        run: |
          cl.exe /O2 cpu_cycles_per_cmd.cpp
          cpu_cycles_per_cmd.exe
          powershell Get-WmiObject win32_physicalmemory
          powershell Get-WmiObject win32_processor
          powershell Get-WmiObject win32_baseboard
          node --version

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cpu_cycles_per_cmd.exe
          path: cpu_cycles_per_cmd.exe
